### ISSUE TITLE
Add instructions to name the class views

### ISSUE THREAD

**Issue by charandas** [encode/rest-framework-tutorial#11]
Tutorial 5 introduces the root API endpoint as:

``` python
@api_view(('GET',))
def api_root(request, format=None):
    return Response({
        'users': reverse('user-list', request=request, format=format),
        'snippets': reverse('snippet-list', request=request, format=format)
    })
```

However, when class based views are introduced in Tutorial 3, we loose the names for the views. We might need something like this for `api-root` view to work:

``` python
url(r'^snippets/$', views.SnippetList.as_view(), name='snippet-list'),
url(r'^users/$', views.UserList.as_view(), name='user-list'),
```

Note the added name parameters for URLConf.

**Comment by davidfrog** [comment]
@charandas Thank you for your second comment. I got tripped up thinking that the code should run at the end of "Creating an endpoint for the highlighted snippets".
