### ISSUE TITLE
Link to tutorial leads to 404

### ISSUE THREAD

**Issue by scottpaulin** [encode/rest-framework-tutorial#35]
The link in the readme leads to a 404. Should the link be updated to http://www.django-rest-framework.org/tutorial/1-serialization/ ?

**Comment by luvejo** [comment]
@scottpaulin, the change was already added at commit [5da6a77](https://github.com/encode/rest-framework-tutorial/commit/5da6a770b8949db1150b695a43a46986300a5e22). I think you can close this issue now.
