### ISSUE TITLE
SnippetDetail and UserDetail returns all snippets - Parts 3 and 4

### ISSUE THREAD

**Issue by evereux** [encode/rest-framework-tutorial#38]
For Parts 3 and 4 of the tutorial the SnippetDetail and UserDetail class views return all objects. I'm not sure if this is intended behaviour, I would think it should be a single item filtered by id? I don't know how I would do that with here though.

[3-class-based-views](http://www.django-rest-framework.org/tutorial/3-class-based-views/)
```
class SnippetDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Snippet.objects.all()
    serializer_class = SnippetSerializer
```

[4-authentication-and-permissions](http://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/)
```
class UserDetail(generics.RetrieveAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer
```

**Comment by tomchristie** [comment]
They only return single instances. The queryset attribute is the queryset against which the fetch is made.
