### ISSUE TITLE
Cannot assign django.contrib.auth.models.AnonymousUser object

### ISSUE THREAD

**Issue by user171** [encode/rest-framework-tutorial#39]
When I try to POST a snippet while not authenticated, Django returns: 

```
ValueError at /snippets/
Cannot assign "<django.contrib.auth.models.AnonymousUser object at 0x7fda1f500470>": "Snippet.owner" must be a "User" instance.
```

Instead I expect something like the sandbox returns:

```
{
    "detail": "Authentication credentials were not provided."
}
```

I have double checked my code and as far as I can tell it is identical to the one in this repository. 

Is there something I missed? 

What is responsible for managing the unauthenticated requests?

Thanks.

**Comment by luvejo** [comment]
Hi. Can you provide your code?

**Comment by user171** [comment]
I have found that adding:

```
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [ 
        'rest_framework.permissions.IsAdminUser',
    ],
    'PAGE_SIZE': 10
}
```
to settings.py solves that.

I have failed to find where it is mentioned in the tutorial.
Did I miss it or should it be added?

**Comment by luvejo** [comment]
Well, I didn't have to. Maybe because I followed the pages code? I'm working right now on updating/improving this repo, anyway.

**Comment by user171** [comment]
@luvejo in my case I have followed the tutorial on the web, starting here: http://www.django-rest-framework.org/tutorial/1-serialization/

I have just found that this setting is showed just before the tutorial, in the quick start, which is a different project.

It is solved for me.
I leave it to you to decide if that should be repeated in the tutorial project or not. I don't really have an opinion.

**Comment by luvejo** [comment]
OK, but you can check my fork, just in case.
