### ISSUE TITLE
Upgrade and Deploy for 3.7 

### ISSUE THREAD

**Issue by carltongibson** [encode/rest-framework-tutorial#41]
Replacing https://github.com/encode/django-rest-framework/issues/5074

**Comment by michaelsbradleyjr** [comment]
Any movement on this? 3.7 was released a month ago and 3.7.3 arrived today.

**Comment by xordoquy** [comment]
@michaelsbradleyjr looking forward PR :)

**Comment by michaelsbradleyjr** [comment]
@xordoquy, seriously? See [#5439](https://github.com/encode/django-rest-framework/issues/5439).

The server on Heroku, which I can't deploy to in any case, is supposed to be DRF's public showcase of the browseable API and auto-documentation related to Core API. Quite simply, that's something the core maintainers ought to keep up with on a regular basis.

**Comment by carltongibson** [comment]
Nice entitlement @michaelsbradleyjr

A PR would help with the “Upgrade” part. Obviously you can’t do the deploy. 

Clearly it would be nice if this project were always spot up to date but the bottom line is it’s very low priority compared to all the other tasks we have on. 

That’s just the reality.

**Comment by xordoquy** [comment]
Reminder: http://www.commitstrip.com/en/2014/05/07/the-truth-behind-open-source-apps/

**Comment by carltongibson** [comment]
@michaelsbradleyjr That's all great. Nothing we don't agree with in theory. Reality is limited maintenance time vs unlimited demands. Priorities. (Software.) 

A PR ensuring this repo was up to date would enable a re-deployment here. (That's the easy bit.)

**Comment by carltongibson** [comment]
That sounds great @jpadilla!

It would be great to have an always updated app in play. (We might have caught the issue with 3.7.2 for a start 😃)

If you want to work your magic we can ping @tomchristie to get you the deploy credentials.

**Comment by jpadilla** [comment]
All good now, thank you all 🎆
