### ISSUE TITLE
corejson not included in the GET dropdown at Api Root

### ISSUE THREAD

**Issue by tunecrew** [encode/rest-framework-tutorial#45]
In **Tutorial 7: Schemas & client libraries**, the [Adding a schema](http://www.django-rest-framework.org/tutorial/7-schemas-and-client-libraries/#adding-a-schema) section says that after installing `coreapi` and updating `urls.py,` `corejson` should be listed as an option in the GET dropdown menu at Api Root.

It does not appear, neither is it present in the sandbox example [here](https://restframework.herokuapp.com/)

**Comment by carltongibson** [comment]
This was addressed in https://github.com/encode/django-rest-framework/pull/5835. 

(Tutorial will be updated on next release.)
