### ISSUE TITLE
NOT NULL constraint failed: snippets_snippet.owner_id

### ISSUE THREAD

**Issue by chatopadhyaye** [encode/rest-framework-tutorial#48]
I am new to the programming and following the tutorial as it is. But can't seem to get past the 4th chapter "Authentication and permissions". At the end of the tutorial I'm trying to create the snippet programmatically but I'm getting error "NOT NULL constraint failed: snippets_snippet.owner_id" . Am I missing something ?

**Comment by xordoquy** [comment]
You probably missed [this section](http://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/#associating-snippets-with-users)
Please note that the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by chatopadhyaye** [comment]
I did as the tutorial said. Apparently "APIView" class has no method named "perform_create()" . So I tried inheriting the view with "CreateAPIView" and "ListCreateAPIView" from generics but to no avail.

**Comment by Tyrannozavr** [comment]
Вероятно мы учим по одному учебнику и вы, возможно, ошиблись там же где и я,  метод perform_create следует объявлять у класса SnippedList, а я его по ошибке в другой запихнул

**Comment by Rafasamarall** [comment]
@shadan76 For people having this problem:
I didn't have follow the exact steps of 3th chapter. All I had to do was put my classes in views exactly the same as was put (using generics.ListCreateAPIView).
