### ISSUE TITLE
redundant import statement in Part 1

### ISSUE THREAD

**Issue by martin-martin** [encode/rest-framework-tutorial#52]
Hello! Thanks for the great tutorial.

I've found a redundant `import` statement in [a section of Pt.1](https://www.django-rest-framework.org/tutorial/1-serialization/#writing-regular-django-views-using-our-serializer) that could be removed:

`from rest_framework.renderers import JSONRenderer`

Thanks, for less typing effort for future learners : )

Happy also to fix it and do a PR if that would help - just not sure where the page is built from.

**Comment by matthewhegarty** [comment]
Thanks.  I checked this out and it is indeed redundant.  I submitted this [PR](https://github.com/encode/django-rest-framework/pull/6543/files)

**Comment by rpkilby** [comment]
Thanks - closing per PR.

**Comment by tomchristie** [comment]
Ah, the sweet smell of collaboration. 🌼
