### ISSUE TITLE
Missing dependancy pyyaml for /schema/

### ISSUE THREAD

**Issue by edn01** [encode/rest-framework-tutorial#57]
Hi,
Great tutorial, thanks for putting it together.  Found one issue in Tutorial 7 (https://www.django-rest-framework.org/tutorial/7-schemas-and-client-libraries/). To get the /schema/ endpoint to work in a browser, the pyyaml package is needed. This needs to be added to requirements.txt and also to the pip install line in the tutorial page above.
Thanks,
Ed

**Comment by matthewhegarty** [comment]
It does tell you to install pyyaml (under ['Adding a schema'](https://www.django-rest-framework.org/tutorial/7-schemas-and-client-libraries/#adding-a-schema)).  Does that cover it?

**Comment by brumar** [comment]
But since the the project has already specific dependencies in `requirements.txt`, it would be misleading to not add pyyaml right? My expectation was that this repository would (almost) work out of the box.

**Comment by xordoquy** [comment]
Closed by 515c325a06137aa3068240058d94a7e7ae920475.
Thanks for the PR.

**Comment by edn01** [comment]
It's in the 'Adding a schema' section (sorry missed it as the second item in the 'pip install' line). Would be good to have it in requirements.txt, like @brumar says, so it works out of the box.
