### ISSUE TITLE
Could not resolve URL for hyperlinked relationship

### ISSUE THREAD

**Issue by ibnshayed** [encode/rest-framework-tutorial#73]
I'm getting the 2 errors while accessing the following urls

{
    "snippets": "http://127.0.0.1:8000/snippets/snippets/",
    "users": "http://127.0.0.1:8000/snippets/users/"
}

Error-1: Could not resolve URL for hyperlinked relationship using view name "snippet-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.

Error-2: Could not resolve URL for hyperlinked relationship using view name "user-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.

**Comment by ibnshayed** [comment]
Solved

`0

fix this issue by modify serializer.py we can define url, such as:

url = serializers.HyperlinkedIdentityField(view_name='snippets:user-detail', lookup_field='pk')
or define in Meta, such as

extra_kwargs = {
    'url': {'view_name': 'snippet:user-detail', 'lookup_field': 'pk'},
}
all serializer.py code:

from rest_framework import serializers
from snippets.models import Snippet
from django.contrib.auth.models import User


class SnippetSerializer(serializers.HyperlinkedModelSerializer):
    owner = serializers.ReadOnlyField(source='owner.username')
    highlight = serializers.HyperlinkedIdentityField(lookup_field="pk", view_name='snippets:snippet-highlight', format='html')

    class Meta:
        model = Snippet
        fields = ('url', 'id', 'highlight', 'owner', 'title', 'code', 'linenos', 'language', 'style')
        extra_kwargs = {
            'url': {'view_name': 'snippets:snippet-detail', 'lookup_field': 'pk'},
        }


class UserSerializer(serializers.HyperlinkedModelSerializer):
    snippets = serializers.HyperlinkedRelatedField(lookup_field="pk", many=True, view_name='snippets:snippet-detail', read_only=True)
    url = serializers.HyperlinkedIdentityField(view_name='snippets:user-detail', lookup_field='pk')

    class Meta:
        model = User
        fields = ('url', 'id', 'username', 'snippets')
        # extra_kwargs = {
        #     'url': {'view_name': 'snippet:user-detail', 'lookup_field': 'pk'},
        # }`

**Comment by ibnshayed** [comment]
my problem is solved but it's very unsatisfied that documentation is not updated

**Comment by carltongibson** [comment]
Hi @ibnshayed — glad you solved your issue. Whilst it's fresh in your mind, a PR improving the tutorial docs is always welcomed! I'm going to close this as it's not really actionable beyond that.
